### ISSUE TITLE
[BUG] Companies dropdown shows duplicates

### ISSUE THREAD

**Issue by LudwikJaniuk** [Klimatbyran/beta#154] opened 2024-06-20 07:22 UTC
E:g. for "JM" or "OX2" there are two entries, one with Q-identifier and one without.

**Comment by Greenheart** [comment] 2024-06-20 07:27
Thanks! This is a known bug caused by the API returning duplicates. We previously had naive filtering on the frontend, but it caused other problems. The real solution is to improve how we fetch companies from OpenSearch (which are then returned by the API). Relevant code (an OpenSearch query): https://github.com/Klimatbyran/garbo/blob/2adf04f9ce7b2d59d41b4ac62ceea372e85d7b48/src/opensearch.ts#L257

**Comment by LudwikJaniuk** [comment] 2024-06-20 13:48
Thanks for the link. That seems more or less fine, only modification I see would be to require the wikidata id to be nonempty in the query. Would that be useful?

The fundamental problem of indexing on wikidata ids is discussed in https://github.com/Klimatbyran/beta/issues/155

**Comment by LudwikJaniuk** [comment] 2024-06-20 14:15
These two examples are solved but the base problem should still be adressed.

**Comment by Greenheart** [comment] 2024-12-16 10:58
This is mostly resolved in the API now. The frontend will still show duplicates if they exist, but this is not as common anymore since we switched to a proper database which only allows one company for each wikidataId.

**Closed by Greenheart** 2024-12-16 10:58 UTC
